name: Update Donors JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # A cada 15 minutos

jobs:
  update-donors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread gspread-pandas
      - name: Run update_donors.py
        run: python src/services/update_donors.py
      - name: Commit donors.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/assets/donors.json
          git commit -m 'Atualiza donors.json via workflow' || echo "No changes to commit"
          git push origin HEAD:gh_pages
